// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pub2sub/pub2sub.proto

package pub2subpb // import "github.com/hpidcock/pub2sub/pkg/pub2subpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublishRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reliable             bool     `protobuf:"varint,4,opt,name=reliable" json:"reliable,omitempty"`
	TopicIds             []string `protobuf:"bytes,5,rep,name=topic_ids,json=topicIds" json:"topic_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{0}
}
func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (dst *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(dst, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PublishRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *PublishRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PublishRequest) GetReliable() bool {
	if m != nil {
		return m.Reliable
	}
	return false
}

func (m *PublishRequest) GetTopicIds() []string {
	if m != nil {
		return m.TopicIds
	}
	return nil
}

type PublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{1}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (dst *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(dst, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

type ReplicateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reliable             bool     `protobuf:"varint,4,opt,name=reliable" json:"reliable,omitempty"`
	TopicId              string   `protobuf:"bytes,5,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	RangeBegin           string   `protobuf:"bytes,6,opt,name=range_begin,json=rangeBegin" json:"range_begin,omitempty"`
	RangeEnd             string   `protobuf:"bytes,7,opt,name=range_end,json=rangeEnd" json:"range_end,omitempty"`
	RangeWidth           int32    `protobuf:"varint,8,opt,name=range_width,json=rangeWidth" json:"range_width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateRequest) Reset()         { *m = ReplicateRequest{} }
func (m *ReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateRequest) ProtoMessage()    {}
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{2}
}
func (m *ReplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRequest.Unmarshal(m, b)
}
func (m *ReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRequest.Marshal(b, m, deterministic)
}
func (dst *ReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRequest.Merge(dst, src)
}
func (m *ReplicateRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateRequest.Size(m)
}
func (m *ReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRequest proto.InternalMessageInfo

func (m *ReplicateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplicateRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *ReplicateRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ReplicateRequest) GetReliable() bool {
	if m != nil {
		return m.Reliable
	}
	return false
}

func (m *ReplicateRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *ReplicateRequest) GetRangeBegin() string {
	if m != nil {
		return m.RangeBegin
	}
	return ""
}

func (m *ReplicateRequest) GetRangeEnd() string {
	if m != nil {
		return m.RangeEnd
	}
	return ""
}

func (m *ReplicateRequest) GetRangeWidth() int32 {
	if m != nil {
		return m.RangeWidth
	}
	return 0
}

type ReplicateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateResponse) Reset()         { *m = ReplicateResponse{} }
func (m *ReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateResponse) ProtoMessage()    {}
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{3}
}
func (m *ReplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateResponse.Unmarshal(m, b)
}
func (m *ReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateResponse.Marshal(b, m, deterministic)
}
func (dst *ReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateResponse.Merge(dst, src)
}
func (m *ReplicateResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateResponse.Size(m)
}
func (m *ReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateResponse proto.InternalMessageInfo

type StreamRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	// If reliable is false, server will ack messages
	// on behalf of the client if send appears to succeed.
	Reliable             bool     `protobuf:"varint,2,opt,name=reliable" json:"reliable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{4}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *StreamRequest) GetReliable() bool {
	if m != nil {
		return m.Reliable
	}
	return false
}

type StreamResponse struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ts       int64  `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
	Message  []byte `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reliable bool   `protobuf:"varint,4,opt,name=reliable" json:"reliable,omitempty"`
	TopicId  string `protobuf:"bytes,5,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	// Empty if reliable is false.
	AckId                string   `protobuf:"bytes,6,opt,name=ack_id,json=ackId" json:"ack_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{5}
}
func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (dst *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(dst, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamResponse) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *StreamResponse) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *StreamResponse) GetReliable() bool {
	if m != nil {
		return m.Reliable
	}
	return false
}

func (m *StreamResponse) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *StreamResponse) GetAckId() string {
	if m != nil {
		return m.AckId
	}
	return ""
}

type AckRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	AckId                string   `protobuf:"bytes,2,opt,name=ack_id,json=ackId" json:"ack_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRequest) Reset()         { *m = AckRequest{} }
func (m *AckRequest) String() string { return proto.CompactTextString(m) }
func (*AckRequest) ProtoMessage()    {}
func (*AckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{6}
}
func (m *AckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRequest.Unmarshal(m, b)
}
func (m *AckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRequest.Marshal(b, m, deterministic)
}
func (dst *AckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRequest.Merge(dst, src)
}
func (m *AckRequest) XXX_Size() int {
	return xxx_messageInfo_AckRequest.Size(m)
}
func (m *AckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AckRequest proto.InternalMessageInfo

func (m *AckRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *AckRequest) GetAckId() string {
	if m != nil {
		return m.AckId
	}
	return ""
}

type AckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{7}
}
func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (dst *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(dst, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

type LeaseRequest struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	TopicId   string `protobuf:"bytes,2,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	// Seconds
	ExpireIn             int64    `protobuf:"varint,3,opt,name=expire_in,json=expireIn" json:"expire_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseRequest) Reset()         { *m = LeaseRequest{} }
func (m *LeaseRequest) String() string { return proto.CompactTextString(m) }
func (*LeaseRequest) ProtoMessage()    {}
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{8}
}
func (m *LeaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseRequest.Unmarshal(m, b)
}
func (m *LeaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseRequest.Marshal(b, m, deterministic)
}
func (dst *LeaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseRequest.Merge(dst, src)
}
func (m *LeaseRequest) XXX_Size() int {
	return xxx_messageInfo_LeaseRequest.Size(m)
}
func (m *LeaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseRequest proto.InternalMessageInfo

func (m *LeaseRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *LeaseRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *LeaseRequest) GetExpireIn() int64 {
	if m != nil {
		return m.ExpireIn
	}
	return 0
}

type LeaseResponse struct {
	// Seconds acquired for.
	Ttl                  int64    `protobuf:"varint,1,opt,name=ttl" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaseResponse) Reset()         { *m = LeaseResponse{} }
func (m *LeaseResponse) String() string { return proto.CompactTextString(m) }
func (*LeaseResponse) ProtoMessage()    {}
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{9}
}
func (m *LeaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaseResponse.Unmarshal(m, b)
}
func (m *LeaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaseResponse.Marshal(b, m, deterministic)
}
func (dst *LeaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaseResponse.Merge(dst, src)
}
func (m *LeaseResponse) XXX_Size() int {
	return xxx_messageInfo_LeaseResponse.Size(m)
}
func (m *LeaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaseResponse proto.InternalMessageInfo

func (m *LeaseResponse) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type InternalPublishRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Ts                   int64    `protobuf:"varint,3,opt,name=ts" json:"ts,omitempty"`
	Message              []byte   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Reliable             bool     `protobuf:"varint,5,opt,name=reliable" json:"reliable,omitempty"`
	TopicId              string   `protobuf:"bytes,6,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalPublishRequest) Reset()         { *m = InternalPublishRequest{} }
func (m *InternalPublishRequest) String() string { return proto.CompactTextString(m) }
func (*InternalPublishRequest) ProtoMessage()    {}
func (*InternalPublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{10}
}
func (m *InternalPublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalPublishRequest.Unmarshal(m, b)
}
func (m *InternalPublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalPublishRequest.Marshal(b, m, deterministic)
}
func (dst *InternalPublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalPublishRequest.Merge(dst, src)
}
func (m *InternalPublishRequest) XXX_Size() int {
	return xxx_messageInfo_InternalPublishRequest.Size(m)
}
func (m *InternalPublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalPublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalPublishRequest proto.InternalMessageInfo

func (m *InternalPublishRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *InternalPublishRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InternalPublishRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *InternalPublishRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *InternalPublishRequest) GetReliable() bool {
	if m != nil {
		return m.Reliable
	}
	return false
}

func (m *InternalPublishRequest) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

type InternalPublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalPublishResponse) Reset()         { *m = InternalPublishResponse{} }
func (m *InternalPublishResponse) String() string { return proto.CompactTextString(m) }
func (*InternalPublishResponse) ProtoMessage()    {}
func (*InternalPublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{11}
}
func (m *InternalPublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalPublishResponse.Unmarshal(m, b)
}
func (m *InternalPublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalPublishResponse.Marshal(b, m, deterministic)
}
func (dst *InternalPublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalPublishResponse.Merge(dst, src)
}
func (m *InternalPublishResponse) XXX_Size() int {
	return xxx_messageInfo_InternalPublishResponse.Size(m)
}
func (m *InternalPublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalPublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalPublishResponse proto.InternalMessageInfo

type InternalAckRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	AckId                string   `protobuf:"bytes,2,opt,name=ack_id,json=ackId" json:"ack_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalAckRequest) Reset()         { *m = InternalAckRequest{} }
func (m *InternalAckRequest) String() string { return proto.CompactTextString(m) }
func (*InternalAckRequest) ProtoMessage()    {}
func (*InternalAckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{12}
}
func (m *InternalAckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalAckRequest.Unmarshal(m, b)
}
func (m *InternalAckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalAckRequest.Marshal(b, m, deterministic)
}
func (dst *InternalAckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalAckRequest.Merge(dst, src)
}
func (m *InternalAckRequest) XXX_Size() int {
	return xxx_messageInfo_InternalAckRequest.Size(m)
}
func (m *InternalAckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalAckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalAckRequest proto.InternalMessageInfo

func (m *InternalAckRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *InternalAckRequest) GetAckId() string {
	if m != nil {
		return m.AckId
	}
	return ""
}

type InternalAckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalAckResponse) Reset()         { *m = InternalAckResponse{} }
func (m *InternalAckResponse) String() string { return proto.CompactTextString(m) }
func (*InternalAckResponse) ProtoMessage()    {}
func (*InternalAckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{13}
}
func (m *InternalAckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalAckResponse.Unmarshal(m, b)
}
func (m *InternalAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalAckResponse.Marshal(b, m, deterministic)
}
func (dst *InternalAckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalAckResponse.Merge(dst, src)
}
func (m *InternalAckResponse) XXX_Size() int {
	return xxx_messageInfo_InternalAckResponse.Size(m)
}
func (m *InternalAckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalAckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalAckResponse proto.InternalMessageInfo

type InternalEvictRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalEvictRequest) Reset()         { *m = InternalEvictRequest{} }
func (m *InternalEvictRequest) String() string { return proto.CompactTextString(m) }
func (*InternalEvictRequest) ProtoMessage()    {}
func (*InternalEvictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{14}
}
func (m *InternalEvictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalEvictRequest.Unmarshal(m, b)
}
func (m *InternalEvictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalEvictRequest.Marshal(b, m, deterministic)
}
func (dst *InternalEvictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalEvictRequest.Merge(dst, src)
}
func (m *InternalEvictRequest) XXX_Size() int {
	return xxx_messageInfo_InternalEvictRequest.Size(m)
}
func (m *InternalEvictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalEvictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalEvictRequest proto.InternalMessageInfo

func (m *InternalEvictRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type InternalEvictResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalEvictResponse) Reset()         { *m = InternalEvictResponse{} }
func (m *InternalEvictResponse) String() string { return proto.CompactTextString(m) }
func (*InternalEvictResponse) ProtoMessage()    {}
func (*InternalEvictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pub2sub_ec0ec734c5132836, []int{15}
}
func (m *InternalEvictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalEvictResponse.Unmarshal(m, b)
}
func (m *InternalEvictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalEvictResponse.Marshal(b, m, deterministic)
}
func (dst *InternalEvictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalEvictResponse.Merge(dst, src)
}
func (m *InternalEvictResponse) XXX_Size() int {
	return xxx_messageInfo_InternalEvictResponse.Size(m)
}
func (m *InternalEvictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalEvictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalEvictResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PublishRequest)(nil), "pub2sub.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "pub2sub.PublishResponse")
	proto.RegisterType((*ReplicateRequest)(nil), "pub2sub.ReplicateRequest")
	proto.RegisterType((*ReplicateResponse)(nil), "pub2sub.ReplicateResponse")
	proto.RegisterType((*StreamRequest)(nil), "pub2sub.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "pub2sub.StreamResponse")
	proto.RegisterType((*AckRequest)(nil), "pub2sub.AckRequest")
	proto.RegisterType((*AckResponse)(nil), "pub2sub.AckResponse")
	proto.RegisterType((*LeaseRequest)(nil), "pub2sub.LeaseRequest")
	proto.RegisterType((*LeaseResponse)(nil), "pub2sub.LeaseResponse")
	proto.RegisterType((*InternalPublishRequest)(nil), "pub2sub.InternalPublishRequest")
	proto.RegisterType((*InternalPublishResponse)(nil), "pub2sub.InternalPublishResponse")
	proto.RegisterType((*InternalAckRequest)(nil), "pub2sub.InternalAckRequest")
	proto.RegisterType((*InternalAckResponse)(nil), "pub2sub.InternalAckResponse")
	proto.RegisterType((*InternalEvictRequest)(nil), "pub2sub.InternalEvictRequest")
	proto.RegisterType((*InternalEvictResponse)(nil), "pub2sub.InternalEvictResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublishServiceClient is the client API for PublishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublishServiceClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type publishServiceClient struct {
	cc *grpc.ClientConn
}

func NewPublishServiceClient(cc *grpc.ClientConn) PublishServiceClient {
	return &publishServiceClient{cc}
}

func (c *publishServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.PublishService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PublishService service

type PublishServiceServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

func RegisterPublishServiceServer(s *grpc.Server, srv PublishServiceServer) {
	s.RegisterService(&_PublishService_serviceDesc, srv)
}

func _PublishService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.PublishService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublishService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pub2sub.PublishService",
	HandlerType: (*PublishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PublishService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pub2sub/pub2sub.proto",
}

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicationServiceClient interface {
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
}

type replicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewReplicationServiceClient(cc *grpc.ClientConn) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.ReplicationService/Replicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ReplicationService service

type ReplicationServiceServer interface {
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
}

func RegisterReplicationServiceServer(s *grpc.Server, srv ReplicationServiceServer) {
	s.RegisterService(&_ReplicationService_serviceDesc, srv)
}

func _ReplicationService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.ReplicationService/Replicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReplicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pub2sub.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replicate",
			Handler:    _ReplicationService_Replicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pub2sub/pub2sub.proto",
}

// SubscribeServiceClient is the client API for SubscribeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscribeServiceClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (SubscribeService_StreamClient, error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error)
}

type subscribeServiceClient struct {
	cc *grpc.ClientConn
}

func NewSubscribeServiceClient(cc *grpc.ClientConn) SubscribeServiceClient {
	return &subscribeServiceClient{cc}
}

func (c *subscribeServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (SubscribeService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SubscribeService_serviceDesc.Streams[0], "/pub2sub.SubscribeService/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscribeServiceStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscribeService_StreamClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type subscribeServiceStreamClient struct {
	grpc.ClientStream
}

func (x *subscribeServiceStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscribeServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.SubscribeService/Ack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeServiceClient) Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error) {
	out := new(LeaseResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.SubscribeService/Lease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SubscribeService service

type SubscribeServiceServer interface {
	Stream(*StreamRequest, SubscribeService_StreamServer) error
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	Lease(context.Context, *LeaseRequest) (*LeaseResponse, error)
}

func RegisterSubscribeServiceServer(s *grpc.Server, srv SubscribeServiceServer) {
	s.RegisterService(&_SubscribeService_serviceDesc, srv)
}

func _SubscribeService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscribeServiceServer).Stream(m, &subscribeServiceStreamServer{stream})
}

type SubscribeService_StreamServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type subscribeServiceStreamServer struct {
	grpc.ServerStream
}

func (x *subscribeServiceStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscribeService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.SubscribeService/Ack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribeService_Lease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServiceServer).Lease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.SubscribeService/Lease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServiceServer).Lease(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubscribeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pub2sub.SubscribeService",
	HandlerType: (*SubscribeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ack",
			Handler:    _SubscribeService_Ack_Handler,
		},
		{
			MethodName: "Lease",
			Handler:    _SubscribeService_Lease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _SubscribeService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pub2sub/pub2sub.proto",
}

// SubscribeInternalServiceClient is the client API for SubscribeInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscribeInternalServiceClient interface {
	InternalPublish(ctx context.Context, in *InternalPublishRequest, opts ...grpc.CallOption) (*InternalPublishResponse, error)
	InternalAck(ctx context.Context, in *InternalAckRequest, opts ...grpc.CallOption) (*InternalAckResponse, error)
	InternalEvict(ctx context.Context, in *InternalEvictRequest, opts ...grpc.CallOption) (*InternalEvictResponse, error)
}

type subscribeInternalServiceClient struct {
	cc *grpc.ClientConn
}

func NewSubscribeInternalServiceClient(cc *grpc.ClientConn) SubscribeInternalServiceClient {
	return &subscribeInternalServiceClient{cc}
}

func (c *subscribeInternalServiceClient) InternalPublish(ctx context.Context, in *InternalPublishRequest, opts ...grpc.CallOption) (*InternalPublishResponse, error) {
	out := new(InternalPublishResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.SubscribeInternalService/InternalPublish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeInternalServiceClient) InternalAck(ctx context.Context, in *InternalAckRequest, opts ...grpc.CallOption) (*InternalAckResponse, error) {
	out := new(InternalAckResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.SubscribeInternalService/InternalAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeInternalServiceClient) InternalEvict(ctx context.Context, in *InternalEvictRequest, opts ...grpc.CallOption) (*InternalEvictResponse, error) {
	out := new(InternalEvictResponse)
	err := c.cc.Invoke(ctx, "/pub2sub.SubscribeInternalService/InternalEvict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SubscribeInternalService service

type SubscribeInternalServiceServer interface {
	InternalPublish(context.Context, *InternalPublishRequest) (*InternalPublishResponse, error)
	InternalAck(context.Context, *InternalAckRequest) (*InternalAckResponse, error)
	InternalEvict(context.Context, *InternalEvictRequest) (*InternalEvictResponse, error)
}

func RegisterSubscribeInternalServiceServer(s *grpc.Server, srv SubscribeInternalServiceServer) {
	s.RegisterService(&_SubscribeInternalService_serviceDesc, srv)
}

func _SubscribeInternalService_InternalPublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeInternalServiceServer).InternalPublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.SubscribeInternalService/InternalPublish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeInternalServiceServer).InternalPublish(ctx, req.(*InternalPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribeInternalService_InternalAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeInternalServiceServer).InternalAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.SubscribeInternalService/InternalAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeInternalServiceServer).InternalAck(ctx, req.(*InternalAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscribeInternalService_InternalEvict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalEvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeInternalServiceServer).InternalEvict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub2sub.SubscribeInternalService/InternalEvict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeInternalServiceServer).InternalEvict(ctx, req.(*InternalEvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubscribeInternalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pub2sub.SubscribeInternalService",
	HandlerType: (*SubscribeInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InternalPublish",
			Handler:    _SubscribeInternalService_InternalPublish_Handler,
		},
		{
			MethodName: "InternalAck",
			Handler:    _SubscribeInternalService_InternalAck_Handler,
		},
		{
			MethodName: "InternalEvict",
			Handler:    _SubscribeInternalService_InternalEvict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pub2sub/pub2sub.proto",
}

func init() { proto.RegisterFile("pub2sub/pub2sub.proto", fileDescriptor_pub2sub_ec0ec734c5132836) }

var fileDescriptor_pub2sub_ec0ec734c5132836 = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0x92, 0xb5, 0x4d, 0xcf, 0xd6, 0xfd, 0xf1, 0xd6, 0x35, 0xcb, 0x7e, 0xfb, 0x2d, 0xe4,
	0xaa, 0x08, 0x69, 0x9b, 0x86, 0xe0, 0x06, 0x6e, 0x56, 0x69, 0x12, 0x45, 0x68, 0x42, 0x19, 0x12,
	0x88, 0x9b, 0x2a, 0x71, 0xac, 0xd6, 0x6a, 0x96, 0x84, 0xd8, 0x1d, 0xdc, 0x73, 0xc7, 0x13, 0xf0,
	0x08, 0xbc, 0x02, 0xaf, 0xc3, 0x93, 0xa0, 0x26, 0xb6, 0x97, 0xa4, 0x1d, 0x54, 0x42, 0x70, 0xd5,
	0xfa, 0x3b, 0x3e, 0x9f, 0xbf, 0xcf, 0xe7, 0x1c, 0x07, 0xba, 0xe9, 0x2c, 0x38, 0x67, 0xb3, 0xe0,
	0x54, 0xfc, 0x9e, 0xa4, 0x59, 0xc2, 0x13, 0xd4, 0x12, 0x4b, 0xf7, 0xb3, 0x06, 0x9b, 0xaf, 0x67,
	0x41, 0x44, 0xd9, 0xc4, 0x23, 0x1f, 0x66, 0x84, 0x71, 0xb4, 0x09, 0x3a, 0x0d, 0x2d, 0xcd, 0xd1,
	0xfa, 0x6d, 0x4f, 0xa7, 0xe1, 0x7c, 0xcd, 0x99, 0xa5, 0x3b, 0x5a, 0xdf, 0xf0, 0x74, 0xce, 0x90,
	0x05, 0xad, 0x1b, 0xc2, 0x98, 0x3f, 0x26, 0x96, 0xe1, 0x68, 0xfd, 0x0d, 0x4f, 0x2e, 0x91, 0x0d,
	0x66, 0x46, 0x22, 0xea, 0x07, 0x11, 0xb1, 0xd6, 0x1c, 0xad, 0x6f, 0x7a, 0x6a, 0x8d, 0x0e, 0xa1,
	0xcd, 0x93, 0x94, 0xe2, 0x11, 0x0d, 0x99, 0xd5, 0x70, 0x8c, 0x7e, 0xdb, 0x33, 0x73, 0x60, 0x18,
	0x32, 0x77, 0x07, 0xb6, 0x94, 0x08, 0x96, 0x26, 0x31, 0x23, 0xee, 0x0f, 0x0d, 0xb6, 0x3d, 0x92,
	0x46, 0x14, 0xfb, 0x9c, 0xfc, 0x5d, 0x69, 0x07, 0x60, 0x4a, 0x69, 0x56, 0x23, 0xe7, 0x6e, 0x09,
	0x65, 0xe8, 0x18, 0xd6, 0x33, 0x3f, 0x1e, 0x93, 0x51, 0x40, 0xc6, 0x34, 0xb6, 0x9a, 0x79, 0x14,
	0x72, 0x68, 0x30, 0x47, 0xe6, 0xb6, 0x8a, 0x0d, 0x24, 0x0e, 0xad, 0x56, 0x1e, 0x36, 0x73, 0xe0,
	0x32, 0x2e, 0x65, 0x7f, 0xa4, 0x21, 0x9f, 0x58, 0xa6, 0xa3, 0xf5, 0x1b, 0x22, 0xfb, 0xed, 0x1c,
	0x71, 0x77, 0x61, 0xa7, 0xe4, 0x51, 0x38, 0x7f, 0x09, 0x9d, 0x6b, 0x9e, 0x11, 0xff, 0x46, 0xba,
	0x3e, 0x02, 0xc0, 0x13, 0x3f, 0x8e, 0x49, 0x34, 0x52, 0xee, 0xdb, 0x02, 0x19, 0x86, 0x15, 0x6b,
	0x7a, 0xd5, 0x9a, 0xfb, 0x55, 0x83, 0x4d, 0x49, 0x56, 0xd0, 0xff, 0xfb, 0x3b, 0xec, 0x42, 0xd3,
	0xc7, 0xd3, 0x79, 0xa0, 0xb8, 0xbe, 0x86, 0x8f, 0xa7, 0xc3, 0xd0, 0x1d, 0x00, 0x5c, 0xe0, 0xe9,
	0x8a, 0x1e, 0xef, 0x38, 0xf4, 0x32, 0x47, 0x07, 0xd6, 0x73, 0x0e, 0x71, 0x73, 0x04, 0x36, 0x5e,
	0x11, 0x9f, 0x91, 0x15, 0x49, 0xcb, 0x9a, 0xf5, 0xaa, 0xe6, 0x43, 0x68, 0x93, 0x4f, 0x29, 0xcd,
	0xc8, 0x88, 0xc6, 0xf9, 0x35, 0x18, 0x9e, 0x59, 0x00, 0xc3, 0xd8, 0x7d, 0x00, 0x1d, 0x71, 0x8c,
	0xb8, 0xd2, 0x6d, 0x30, 0x38, 0x8f, 0xf2, 0x03, 0x0c, 0x6f, 0xfe, 0xd7, 0xfd, 0xa6, 0xc1, 0xfe,
	0x30, 0xe6, 0x24, 0x8b, 0xfd, 0xa8, 0x36, 0x5e, 0xbf, 0x11, 0x55, 0x94, 0x47, 0xaf, 0x95, 0xc7,
	0x58, 0x56, 0x9e, 0xb5, 0xfb, 0xcb, 0xd3, 0xf8, 0x45, 0x79, 0x9a, 0x15, 0xab, 0xee, 0x01, 0xf4,
	0x16, 0x94, 0xaa, 0x4e, 0x44, 0x32, 0xf4, 0xc7, 0xa5, 0xea, 0xc2, 0x6e, 0x85, 0x4b, 0x1c, 0xf1,
	0x04, 0xf6, 0x24, 0x7c, 0x79, 0x4b, 0x31, 0x5f, 0xed, 0x10, 0xb7, 0x07, 0xdd, 0x5a, 0x5a, 0xc1,
	0x77, 0x7e, 0xa5, 0x9e, 0xb3, 0x6b, 0x92, 0xdd, 0x52, 0x4c, 0xd0, 0x73, 0x68, 0x09, 0x04, 0xf5,
	0x4e, 0xe4, 0x2b, 0x58, 0xad, 0x89, 0x6d, 0x2d, 0x06, 0x04, 0xdf, 0x3b, 0x40, 0x72, 0x42, 0x69,
	0x12, 0x4b, 0xce, 0x01, 0xb4, 0xd5, 0xdc, 0xa2, 0x03, 0x95, 0x5c, 0x7f, 0xaf, 0x6c, 0x7b, 0x59,
	0x48, 0x30, 0x7f, 0xd7, 0x60, 0xfb, 0x7a, 0x16, 0x30, 0x9c, 0xd1, 0x80, 0x48, 0xe2, 0x67, 0xd0,
	0x2c, 0xc6, 0x15, 0xed, 0xab, 0xd4, 0xca, 0x63, 0x60, 0xf7, 0x16, 0xf0, 0x82, 0xef, 0x4c, 0x43,
	0x67, 0x60, 0x5c, 0xe0, 0x29, 0xda, 0x55, 0x3b, 0xee, 0x8a, 0x66, 0xef, 0x55, 0x41, 0xd1, 0xb8,
	0x4f, 0xa1, 0x91, 0x77, 0x32, 0xea, 0xaa, 0x70, 0x79, 0x80, 0xec, 0xfd, 0x3a, 0x2c, 0xb4, 0x7f,
	0xd1, 0xc1, 0x52, 0xda, 0x65, 0x21, 0xa4, 0x87, 0x37, 0xb0, 0x55, 0x6b, 0x28, 0x74, 0xac, 0x78,
	0x96, 0x0f, 0x85, 0xed, 0xdc, 0xbf, 0x41, 0x48, 0x7d, 0x01, 0xeb, 0xa5, 0xfe, 0x41, 0x87, 0x0b,
	0x09, 0x25, 0xb3, 0xff, 0x2d, 0x0f, 0x0a, 0xa6, 0x2b, 0xe8, 0x54, 0x7a, 0x07, 0x1d, 0x2d, 0x6c,
	0x2f, 0xb7, 0xa2, 0xfd, 0xff, 0x7d, 0xe1, 0x82, 0x6f, 0xf0, 0xe8, 0xfd, 0xc3, 0x31, 0xe5, 0x93,
	0x59, 0x70, 0x82, 0x93, 0x9b, 0xd3, 0x49, 0x4a, 0x43, 0x9c, 0xe0, 0xe9, 0xa9, 0xfa, 0xf0, 0x4e,
	0xc7, 0xf2, 0x7f, 0x1a, 0x04, 0xcd, 0xfc, 0xfb, 0xfb, 0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9e, 0x99, 0x71, 0x66, 0x98, 0x07, 0x00, 0x00,
}
