// Code generated by protoc-gen-twirp v5.4.0, DO NOT EDIT.
// source: pub2sub/pub2sub.proto

/*
Package pub2subpb is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.4.0.

It is generated from these files:
	pub2sub/pub2sub.proto
*/
package pub2subpb

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import strconv "strconv"
import json "encoding/json"
import url "net/url"

// ========================
// PublishService Interface
// ========================

type PublishService interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

// ==============================
// PublishService Protobuf Client
// ==============================

type publishServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPublishServiceProtobufClient creates a Protobuf client that implements the PublishService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPublishServiceProtobufClient(addr string, client HTTPClient) PublishService {
	prefix := urlBase(addr) + PublishServicePathPrefix
	urls := [1]string{
		prefix + "Publish",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &publishServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &publishServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *publishServiceProtobufClient) Publish(ctx context.Context, in *PublishRequest) (*PublishResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "PublishService")
	ctx = ctxsetters.WithMethodName(ctx, "Publish")
	out := new(PublishResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==========================
// PublishService JSON Client
// ==========================

type publishServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewPublishServiceJSONClient creates a JSON client that implements the PublishService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPublishServiceJSONClient(addr string, client HTTPClient) PublishService {
	prefix := urlBase(addr) + PublishServicePathPrefix
	urls := [1]string{
		prefix + "Publish",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &publishServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &publishServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *publishServiceJSONClient) Publish(ctx context.Context, in *PublishRequest) (*PublishResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "PublishService")
	ctx = ctxsetters.WithMethodName(ctx, "Publish")
	out := new(PublishResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =============================
// PublishService Server Handler
// =============================

type publishServiceServer struct {
	PublishService
	hooks *twirp.ServerHooks
}

func NewPublishServiceServer(svc PublishService, hooks *twirp.ServerHooks) TwirpServer {
	return &publishServiceServer{
		PublishService: svc,
		hooks:          hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *publishServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// PublishServicePathPrefix is used for all URL paths on a twirp PublishService server.
// Requests are always: POST PublishServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const PublishServicePathPrefix = "/twirp/pub2sub.PublishService/"

func (s *publishServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "PublishService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/pub2sub.PublishService/Publish":
		s.servePublish(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *publishServiceServer) servePublish(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePublishJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePublishProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *publishServiceServer) servePublishJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Publish")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(PublishRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PublishResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Publish(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PublishResponse and nil error while calling Publish. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *publishServiceServer) servePublishProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Publish")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(PublishRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *PublishResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Publish(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PublishResponse and nil error while calling Publish. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *publishServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *publishServiceServer) ProtocGenTwirpVersion() string {
	return "v5.4.0"
}

// ============================
// ReplicationService Interface
// ============================

type ReplicationService interface {
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
}

// ==================================
// ReplicationService Protobuf Client
// ==================================

type replicationServiceProtobufClient struct {
	client HTTPClient
	urls   [1]string
}

// NewReplicationServiceProtobufClient creates a Protobuf client that implements the ReplicationService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewReplicationServiceProtobufClient(addr string, client HTTPClient) ReplicationService {
	prefix := urlBase(addr) + ReplicationServicePathPrefix
	urls := [1]string{
		prefix + "Replicate",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &replicationServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &replicationServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *replicationServiceProtobufClient) Replicate(ctx context.Context, in *ReplicateRequest) (*ReplicateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "ReplicationService")
	ctx = ctxsetters.WithMethodName(ctx, "Replicate")
	out := new(ReplicateResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// ==============================
// ReplicationService JSON Client
// ==============================

type replicationServiceJSONClient struct {
	client HTTPClient
	urls   [1]string
}

// NewReplicationServiceJSONClient creates a JSON client that implements the ReplicationService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewReplicationServiceJSONClient(addr string, client HTTPClient) ReplicationService {
	prefix := urlBase(addr) + ReplicationServicePathPrefix
	urls := [1]string{
		prefix + "Replicate",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &replicationServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &replicationServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *replicationServiceJSONClient) Replicate(ctx context.Context, in *ReplicateRequest) (*ReplicateResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "ReplicationService")
	ctx = ctxsetters.WithMethodName(ctx, "Replicate")
	out := new(ReplicateResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

// =================================
// ReplicationService Server Handler
// =================================

type replicationServiceServer struct {
	ReplicationService
	hooks *twirp.ServerHooks
}

func NewReplicationServiceServer(svc ReplicationService, hooks *twirp.ServerHooks) TwirpServer {
	return &replicationServiceServer{
		ReplicationService: svc,
		hooks:              hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *replicationServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// ReplicationServicePathPrefix is used for all URL paths on a twirp ReplicationService server.
// Requests are always: POST ReplicationServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const ReplicationServicePathPrefix = "/twirp/pub2sub.ReplicationService/"

func (s *replicationServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "ReplicationService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/pub2sub.ReplicationService/Replicate":
		s.serveReplicate(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *replicationServiceServer) serveReplicate(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveReplicateJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveReplicateProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *replicationServiceServer) serveReplicateJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Replicate")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ReplicateRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ReplicateResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Replicate(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ReplicateResponse and nil error while calling Replicate. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *replicationServiceServer) serveReplicateProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Replicate")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ReplicateRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ReplicateResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Replicate(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ReplicateResponse and nil error while calling Replicate. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *replicationServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 1
}

func (s *replicationServiceServer) ProtocGenTwirpVersion() string {
	return "v5.4.0"
}

// ==========================
// SubscribeService Interface
// ==========================

type SubscribeService interface {
	Stream(context.Context, *StreamRequest) (*StreamResponse, error)

	Ack(context.Context, *AckRequest) (*AckResponse, error)

	Lease(context.Context, *LeaseRequest) (*LeaseResponse, error)
}

// ================================
// SubscribeService Protobuf Client
// ================================

type subscribeServiceProtobufClient struct {
	client HTTPClient
	urls   [3]string
}

// NewSubscribeServiceProtobufClient creates a Protobuf client that implements the SubscribeService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewSubscribeServiceProtobufClient(addr string, client HTTPClient) SubscribeService {
	prefix := urlBase(addr) + SubscribeServicePathPrefix
	urls := [3]string{
		prefix + "Stream",
		prefix + "Ack",
		prefix + "Lease",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &subscribeServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &subscribeServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *subscribeServiceProtobufClient) Stream(ctx context.Context, in *StreamRequest) (*StreamResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Stream")
	out := new(StreamResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *subscribeServiceProtobufClient) Ack(ctx context.Context, in *AckRequest) (*AckResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Ack")
	out := new(AckResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *subscribeServiceProtobufClient) Lease(ctx context.Context, in *LeaseRequest) (*LeaseResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Lease")
	out := new(LeaseResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

// ============================
// SubscribeService JSON Client
// ============================

type subscribeServiceJSONClient struct {
	client HTTPClient
	urls   [3]string
}

// NewSubscribeServiceJSONClient creates a JSON client that implements the SubscribeService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewSubscribeServiceJSONClient(addr string, client HTTPClient) SubscribeService {
	prefix := urlBase(addr) + SubscribeServicePathPrefix
	urls := [3]string{
		prefix + "Stream",
		prefix + "Ack",
		prefix + "Lease",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &subscribeServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &subscribeServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *subscribeServiceJSONClient) Stream(ctx context.Context, in *StreamRequest) (*StreamResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Stream")
	out := new(StreamResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *subscribeServiceJSONClient) Ack(ctx context.Context, in *AckRequest) (*AckResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Ack")
	out := new(AckResponse)
	err := doJSONRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *subscribeServiceJSONClient) Lease(ctx context.Context, in *LeaseRequest) (*LeaseResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithMethodName(ctx, "Lease")
	out := new(LeaseResponse)
	err := doJSONRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

// ===============================
// SubscribeService Server Handler
// ===============================

type subscribeServiceServer struct {
	SubscribeService
	hooks *twirp.ServerHooks
}

func NewSubscribeServiceServer(svc SubscribeService, hooks *twirp.ServerHooks) TwirpServer {
	return &subscribeServiceServer{
		SubscribeService: svc,
		hooks:            hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *subscribeServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// SubscribeServicePathPrefix is used for all URL paths on a twirp SubscribeService server.
// Requests are always: POST SubscribeServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const SubscribeServicePathPrefix = "/twirp/pub2sub.SubscribeService/"

func (s *subscribeServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/pub2sub.SubscribeService/Stream":
		s.serveStream(ctx, resp, req)
		return
	case "/twirp/pub2sub.SubscribeService/Ack":
		s.serveAck(ctx, resp, req)
		return
	case "/twirp/pub2sub.SubscribeService/Lease":
		s.serveLease(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *subscribeServiceServer) serveStream(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveStreamJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveStreamProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeServiceServer) serveStreamJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Stream")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(StreamRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *StreamResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Stream(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *StreamResponse and nil error while calling Stream. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) serveStreamProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Stream")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(StreamRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *StreamResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Stream(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *StreamResponse and nil error while calling Stream. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) serveAck(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAckJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAckProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeServiceServer) serveAckJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Ack")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(AckRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AckResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Ack(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AckResponse and nil error while calling Ack. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) serveAckProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Ack")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(AckRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *AckResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Ack(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AckResponse and nil error while calling Ack. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) serveLease(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveLeaseJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveLeaseProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeServiceServer) serveLeaseJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Lease")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(LeaseRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *LeaseResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Lease(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *LeaseResponse and nil error while calling Lease. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) serveLeaseProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Lease")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(LeaseRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *LeaseResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.Lease(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *LeaseResponse and nil error while calling Lease. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 2
}

func (s *subscribeServiceServer) ProtocGenTwirpVersion() string {
	return "v5.4.0"
}

// ==================================
// SubscribeInternalService Interface
// ==================================

type SubscribeInternalService interface {
	InternalPublish(context.Context, *InternalPublishRequest) (*InternalPublishResponse, error)

	InternalAck(context.Context, *InternalAckRequest) (*InternalAckResponse, error)

	InternalEvict(context.Context, *InternalEvictRequest) (*InternalEvictResponse, error)
}

// ========================================
// SubscribeInternalService Protobuf Client
// ========================================

type subscribeInternalServiceProtobufClient struct {
	client HTTPClient
	urls   [3]string
}

// NewSubscribeInternalServiceProtobufClient creates a Protobuf client that implements the SubscribeInternalService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewSubscribeInternalServiceProtobufClient(addr string, client HTTPClient) SubscribeInternalService {
	prefix := urlBase(addr) + SubscribeInternalServicePathPrefix
	urls := [3]string{
		prefix + "InternalPublish",
		prefix + "InternalAck",
		prefix + "InternalEvict",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &subscribeInternalServiceProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &subscribeInternalServiceProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *subscribeInternalServiceProtobufClient) InternalPublish(ctx context.Context, in *InternalPublishRequest) (*InternalPublishResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalPublish")
	out := new(InternalPublishResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *subscribeInternalServiceProtobufClient) InternalAck(ctx context.Context, in *InternalAckRequest) (*InternalAckResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalAck")
	out := new(InternalAckResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *subscribeInternalServiceProtobufClient) InternalEvict(ctx context.Context, in *InternalEvictRequest) (*InternalEvictResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalEvict")
	out := new(InternalEvictResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

// ====================================
// SubscribeInternalService JSON Client
// ====================================

type subscribeInternalServiceJSONClient struct {
	client HTTPClient
	urls   [3]string
}

// NewSubscribeInternalServiceJSONClient creates a JSON client that implements the SubscribeInternalService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewSubscribeInternalServiceJSONClient(addr string, client HTTPClient) SubscribeInternalService {
	prefix := urlBase(addr) + SubscribeInternalServicePathPrefix
	urls := [3]string{
		prefix + "InternalPublish",
		prefix + "InternalAck",
		prefix + "InternalEvict",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &subscribeInternalServiceJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &subscribeInternalServiceJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *subscribeInternalServiceJSONClient) InternalPublish(ctx context.Context, in *InternalPublishRequest) (*InternalPublishResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalPublish")
	out := new(InternalPublishResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *subscribeInternalServiceJSONClient) InternalAck(ctx context.Context, in *InternalAckRequest) (*InternalAckResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalAck")
	out := new(InternalAckResponse)
	err := doJSONRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *subscribeInternalServiceJSONClient) InternalEvict(ctx context.Context, in *InternalEvictRequest) (*InternalEvictResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithMethodName(ctx, "InternalEvict")
	out := new(InternalEvictResponse)
	err := doJSONRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

// =======================================
// SubscribeInternalService Server Handler
// =======================================

type subscribeInternalServiceServer struct {
	SubscribeInternalService
	hooks *twirp.ServerHooks
}

func NewSubscribeInternalServiceServer(svc SubscribeInternalService, hooks *twirp.ServerHooks) TwirpServer {
	return &subscribeInternalServiceServer{
		SubscribeInternalService: svc,
		hooks: hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *subscribeInternalServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// SubscribeInternalServicePathPrefix is used for all URL paths on a twirp SubscribeInternalService server.
// Requests are always: POST SubscribeInternalServicePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const SubscribeInternalServicePathPrefix = "/twirp/pub2sub.SubscribeInternalService/"

func (s *subscribeInternalServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "pub2sub")
	ctx = ctxsetters.WithServiceName(ctx, "SubscribeInternalService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/pub2sub.SubscribeInternalService/InternalPublish":
		s.serveInternalPublish(ctx, resp, req)
		return
	case "/twirp/pub2sub.SubscribeInternalService/InternalAck":
		s.serveInternalAck(ctx, resp, req)
		return
	case "/twirp/pub2sub.SubscribeInternalService/InternalEvict":
		s.serveInternalEvict(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *subscribeInternalServiceServer) serveInternalPublish(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInternalPublishJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInternalPublishProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeInternalServiceServer) serveInternalPublishJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalPublish")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(InternalPublishRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalPublishResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalPublish(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalPublishResponse and nil error while calling InternalPublish. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) serveInternalPublishProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalPublish")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(InternalPublishRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalPublishResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalPublish(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalPublishResponse and nil error while calling InternalPublish. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) serveInternalAck(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInternalAckJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInternalAckProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeInternalServiceServer) serveInternalAckJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalAck")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(InternalAckRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalAckResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalAck(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalAckResponse and nil error while calling InternalAck. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) serveInternalAckProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalAck")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(InternalAckRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalAckResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalAck(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalAckResponse and nil error while calling InternalAck. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) serveInternalEvict(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveInternalEvictJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveInternalEvictProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *subscribeInternalServiceServer) serveInternalEvictJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalEvict")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(InternalEvictRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalEvictResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalEvict(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalEvictResponse and nil error while calling InternalEvict. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) serveInternalEvictProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "InternalEvict")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(InternalEvictRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *InternalEvictResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.InternalEvict(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *InternalEvictResponse and nil error while calling InternalEvict. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *subscribeInternalServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 3
}

func (s *subscribeInternalServiceServer) ProtocGenTwirpVersion() string {
	return "v5.4.0"
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
}

// WriteError writes an HTTP response with a valid Twirp error format.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON (instead of protobuf)
	resp.WriteHeader(statusCode)                          // HTTP response status code

	respBody := marshalErrorToJSON(twerr)
	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.4.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read server error response body", err)
	}
	var tj twerrJSON
	if err := json.Unmarshal(respBodyBytes, &tj); err != nil {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg)
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}
func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrappedError implements the github.com/pkg/errors.Causer interface, allowing errors to be
// examined for their root cause.
type wrappedError struct {
	msg   string
	cause error
}

func wrapErr(err error, msg string) error { return &wrappedError{msg: msg, cause: err} }
func (e *wrappedError) Cause() error      { return e.cause }
func (e *wrappedError) Error() string     { return e.msg + ": " + e.cause.Error() }

// clientError adds consistency to errors generated in the client
func clientError(desc string, err error) twirp.Error {
	return twirp.InternalErrorWith(wrapErr(err, desc))
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest is common code to make a request to the remote twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return clientError("failed to marshal proto request", err)
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read response body", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return clientError("failed to unmarshal proto response", err)
	}
	return nil
}

// doJSONRequest is common code to make a request to the remote twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return clientError("failed to marshal json request", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return clientError("failed to unmarshal json response", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}
	return nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xd2, 0xb5, 0x4d, 0xcf, 0xd6, 0xfd, 0x78, 0xeb, 0xea, 0x65, 0x8c, 0x45, 0xb9, 0x2a,
	0x42, 0xda, 0xa6, 0x21, 0xb8, 0x81, 0x9b, 0x55, 0x9a, 0x44, 0x11, 0x9a, 0x50, 0x86, 0x04, 0xe2,
	0xa6, 0x4a, 0x1c, 0xab, 0xb5, 0xda, 0x39, 0x21, 0x4e, 0x07, 0xf7, 0xdc, 0xf1, 0x04, 0x3c, 0x02,
	0xaf, 0xc0, 0xeb, 0xf0, 0x24, 0xa8, 0x89, 0xed, 0x25, 0x69, 0x07, 0x95, 0x10, 0x5c, 0xb5, 0xfe,
	0x8e, 0xcf, 0xe7, 0xef, 0xf3, 0x39, 0xc7, 0x81, 0x4e, 0x3c, 0x0b, 0xce, 0xc5, 0x2c, 0x38, 0x95,
	0xbf, 0x27, 0x71, 0x12, 0xa5, 0x11, 0x6a, 0xca, 0xa5, 0xfb, 0xc5, 0x80, 0xcd, 0x37, 0xb3, 0x60,
	0xca, 0xc4, 0xd8, 0xa3, 0x1f, 0x67, 0x54, 0xa4, 0x68, 0x13, 0x4c, 0x16, 0x62, 0xc3, 0x31, 0x7a,
	0x2d, 0xcf, 0x64, 0xe1, 0x7c, 0x9d, 0x0a, 0x6c, 0x3a, 0x46, 0xaf, 0xe6, 0x99, 0xa9, 0x40, 0x18,
	0x9a, 0x37, 0x54, 0x08, 0x7f, 0x44, 0x71, 0xcd, 0x31, 0x7a, 0x1b, 0x9e, 0x5a, 0x22, 0x1b, 0xac,
	0x84, 0x4e, 0x99, 0x1f, 0x4c, 0x29, 0x5e, 0x73, 0x8c, 0x9e, 0xe5, 0xe9, 0x35, 0x3a, 0x84, 0x56,
	0x1a, 0xc5, 0x8c, 0x0c, 0x59, 0x28, 0x70, 0xdd, 0xa9, 0xf5, 0x5a, 0x9e, 0x95, 0x01, 0x83, 0x50,
	0xb8, 0x3b, 0xb0, 0xa5, 0x45, 0x88, 0x38, 0xe2, 0x82, 0xba, 0x3f, 0x0d, 0xd8, 0xf6, 0x68, 0x3c,
	0x65, 0xc4, 0x4f, 0xe9, 0xbf, 0x95, 0x76, 0x00, 0x96, 0x92, 0x86, 0xeb, 0x19, 0x77, 0x53, 0x2a,
	0x43, 0xc7, 0xb0, 0x9e, 0xf8, 0x7c, 0x44, 0x87, 0x01, 0x1d, 0x31, 0x8e, 0x1b, 0x59, 0x14, 0x32,
	0xa8, 0x3f, 0x47, 0xe6, 0xb6, 0xf2, 0x0d, 0x94, 0x87, 0xb8, 0x99, 0x85, 0xad, 0x0c, 0xb8, 0xe4,
	0x85, 0xec, 0x4f, 0x2c, 0x4c, 0xc7, 0xd8, 0x72, 0x8c, 0x5e, 0x5d, 0x66, 0xbf, 0x9b, 0x23, 0xee,
	0x2e, 0xec, 0x14, 0x3c, 0x4a, 0xe7, 0xaf, 0xa0, 0x7d, 0x9d, 0x26, 0xd4, 0xbf, 0x51, 0xae, 0x8f,
	0x00, 0xc8, 0xd8, 0xe7, 0x9c, 0x4e, 0x87, 0xda, 0x7d, 0x4b, 0x22, 0x83, 0xb0, 0x64, 0xcd, 0x2c,
	0x5b, 0x73, 0xbf, 0x19, 0xb0, 0xa9, 0xc8, 0x72, 0xfa, 0xff, 0x7f, 0x87, 0x1d, 0x68, 0xf8, 0x64,
	0x32, 0x0f, 0xe4, 0xd7, 0x57, 0xf7, 0xc9, 0x64, 0x10, 0xba, 0x7d, 0x80, 0x0b, 0x32, 0x59, 0xd1,
	0xe3, 0x1d, 0x87, 0x59, 0xe4, 0x68, 0xc3, 0x7a, 0xc6, 0x21, 0x6f, 0x8e, 0xc2, 0xc6, 0x6b, 0xea,
	0x0b, 0xba, 0x22, 0x69, 0x51, 0xb3, 0x59, 0xd6, 0x7c, 0x08, 0x2d, 0xfa, 0x39, 0x66, 0x09, 0x1d,
	0x32, 0x9e, 0x5d, 0x43, 0xcd, 0xb3, 0x72, 0x60, 0xc0, 0xdd, 0x2d, 0x68, 0xcb, 0x63, 0xe4, 0xb9,
	0xdf, 0x0d, 0xd8, 0x1f, 0xf0, 0x94, 0x26, 0xdc, 0x9f, 0x56, 0x86, 0xe9, 0x0f, 0x12, 0xf2, 0x62,
	0x98, 0x95, 0x62, 0xd4, 0x96, 0x15, 0x63, 0xed, 0xfe, 0x62, 0xd4, 0x7f, 0x53, 0x8c, 0x46, 0xc9,
	0x98, 0x7b, 0x00, 0xdd, 0x05, 0xa5, 0xba, 0xef, 0x90, 0x0a, 0xfd, 0x75, 0x61, 0x3a, 0xb0, 0x5b,
	0xe2, 0x92, 0x47, 0x3c, 0x85, 0x3d, 0x05, 0x5f, 0xde, 0x32, 0x92, 0xae, 0x76, 0x88, 0xdb, 0x85,
	0x4e, 0x25, 0x2d, 0xe7, 0x3b, 0xbf, 0xd2, 0x8f, 0xd7, 0x35, 0x4d, 0x6e, 0x19, 0xa1, 0xe8, 0x05,
	0x34, 0x25, 0x82, 0xba, 0x27, 0xea, 0xcd, 0x2b, 0xd7, 0xc4, 0xc6, 0x8b, 0x01, 0xc9, 0xf7, 0x1e,
	0x90, 0x9a, 0x47, 0x16, 0x71, 0xc5, 0xd9, 0x87, 0x96, 0x9e, 0x52, 0x74, 0xa0, 0x93, 0xab, 0xaf,
	0x93, 0x6d, 0x2f, 0x0b, 0x49, 0xe6, 0x1f, 0x06, 0x6c, 0x5f, 0xcf, 0x02, 0x41, 0x12, 0x16, 0x50,
	0x45, 0xfc, 0x1c, 0x1a, 0xf9, 0x70, 0xa2, 0x7d, 0x9d, 0x5a, 0x1a, 0x7d, 0xbb, 0xbb, 0x80, 0xe7,
	0x7c, 0x67, 0x06, 0x3a, 0x83, 0xda, 0x05, 0x99, 0xa0, 0x5d, 0xbd, 0xe3, 0xae, 0x68, 0xf6, 0x5e,
	0x19, 0x94, 0x93, 0xff, 0x0c, 0xea, 0x59, 0xdf, 0xa2, 0x8e, 0x0e, 0x17, 0xc7, 0xc5, 0xde, 0xaf,
	0xc2, 0x52, 0xfb, 0x57, 0x13, 0xb0, 0xd6, 0xae, 0x0a, 0xa1, 0x3c, 0xbc, 0x85, 0xad, 0x4a, 0x43,
	0xa1, 0x63, 0xcd, 0xb3, 0x7c, 0x28, 0x6c, 0xe7, 0xfe, 0x0d, 0x52, 0xea, 0x4b, 0x58, 0x2f, 0xf4,
	0x0f, 0x3a, 0x5c, 0x48, 0x28, 0x98, 0x7d, 0xb0, 0x3c, 0x28, 0x99, 0xae, 0xa0, 0x5d, 0xea, 0x1d,
	0x74, 0xb4, 0xb0, 0xbd, 0xd8, 0x8a, 0xf6, 0xc3, 0xfb, 0xc2, 0x39, 0x5f, 0xff, 0xf1, 0x87, 0x47,
	0x23, 0x96, 0x8e, 0x67, 0xc1, 0x09, 0x89, 0x6e, 0x4e, 0xc7, 0x31, 0x0b, 0x49, 0x44, 0x26, 0xa7,
	0xfa, 0x33, 0x3b, 0x19, 0xa9, 0xff, 0x71, 0x10, 0x34, 0xb2, 0xaf, 0xed, 0x93, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0xcc, 0xc9, 0x37, 0x86, 0x07, 0x00, 0x00,
}
