package topic

import "github.com/gobuffalo/packr"

// !!! GENERATED FILE !!!
// Do NOT hand edit this file!!
// It is recommended that you DO NOT check into this file into SCM.
// We STRONGLY recommend you delete this file after you have built your
// Go binary. You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("./lua", "add_to_topic.lua", "\"bG9jYWwgdG9waWNJRCA9IEtFWVNbMV0KbG9jYWwgZXhwaXJlQXQgPSBBUkdWWzFdCmxvY2FsIGNoYW5uZWxJRCA9IEFSR1ZbMl0KcmVzID0gcmVkaXMuY2FsbCgnemFkZCcsIHRvcGljSUQsICdOWCcsICcwJywgY2hhbm5lbElEKQppZiByZXMgPT0gMCB0aGVuCiAgICByZXR1cm4gMAplbmQKbG9jYWwgYyA9IHRvbnVtYmVyKHJlZGlzLmNhbGwoJ3R0bCcsIHRvcGljSUQpKQppZiBjIDwgMCB0aGVuCiAgICByZWRpcy5jYWxsKCdleHBpcmVhdCcsIHRvcGljSUQsIGV4cGlyZUF0KQplbmQKcmV0dXJuIDEK\"")
		packr.PackJSONBytes("./lua", "create_or_extend_queue.lua", "\"bG9jYWwgY2hhbm5lbElEID0gS0VZU1sxXQpsb2NhbCBleHBpcmVJbiA9IEFSR1ZbMV0KbG9jYWwgYyA9IHRvbnVtYmVyKHJlZGlzLmNhbGwoJ3R0bCcsIGNoYW5uZWxJRCkpCmlmIGMgfj0gLTIgdGhlbgogICAgbG9jYWwgbiA9IHRvbnVtYmVyKGV4cGlyZUluKQogICAgaWYgYyA+PSAwIGFuZCBuIDwgYyB0aGVuCiAgICAgICAgcmV0dXJuIDEKICAgIGVuZAogICAgcmVkaXMuY2FsbCgnZXhwaXJlJywgY2hhbm5lbElELCBleHBpcmVJbikKICAgIHJldHVybiAxCmVuZApyZWRpcy5jYWxsKCd4YWRkJywgY2hhbm5lbElELCAnMC0xJywgJ25ld19xdWV1ZScsICcwJykKcmVkaXMuY2FsbCgnZXhwaXJlJywgY2hhbm5lbElELCBleHBpcmVJbikKcmV0dXJuIDEK\"")
		packr.PackJSONBytes("./lua", "extend_queue.lua", "\"bG9jYWwgY2hhbm5lbElEID0gS0VZU1sxXQpsb2NhbCBleHBpcmVJbiA9IEFSR1ZbMV0KbG9jYWwgYyA9IHRvbnVtYmVyKHJlZGlzLmNhbGwoJ3R0bCcsIGNoYW5uZWxJRCkpCmlmIGMgPT0gLTIgdGhlbgogICAgcmV0dXJuIDAKZW5kCmxvY2FsIG4gPSB0b251bWJlcihleHBpcmVJbikKaWYgYyB+PSAtMSBhbmQgbiA8IGMgdGhlbgogICAgcmV0dXJuIDEKZW5kCnJlZGlzLmNhbGwoJ2V4cGlyZScsIGNoYW5uZWxJRCwgZXhwaXJlSW4pCnJldHVybiAxCg==\"")
		packr.PackJSONBytes("./lua", "push_if_exists.lua", "\"bG9jYWwgY2hhbm5lbElEID0gS0VZU1sxXQpsb2NhbCBleGlzdHMgPSByZWRpcy5jYWxsKCdleGlzdHMnLCBjaGFubmVsSUQpCmlmIGV4aXN0cyA9PSAwIHRoZW4KICAgIHJldHVybiBuaWwKZW5kCnJldHVybiByZWRpcy5jYWxsKCd4YWRkJywgY2hhbm5lbElELCAnKicsIHVucGFjayhBUkdTKSkK\"")
}
